'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class book_info

    <Key>
    Public Property bookinfo_id As Integer

    <Required>
    <Display(Name:="Book Title")>
    Public Property book_title As String

    <Required>
    <Display(Name:="Edition")>
    Public Property book_edition As String

    <Required>
    <Display(Name:="ISBN")>
    Public Property book_isbn As String

    <Required>
    <Display(Name:="Author")>
    Public Property book_author As String

    Public Overridable Property books As ICollection(Of book) = New HashSet(Of book)

End Class
