'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class book
    Public Property book_id As Integer
    Public Property user_id As Integer
    Public Property bookinfo_id As Integer

    Public Overridable Property book_info As book_info
    Public Overridable Property user As user

End Class
