'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class book_info
    Public Property bookinfo_id As Integer
    Public Property book_title As String
    Public Property book_edition As String
    Public Property book_isbn As String
    Public Property book_author As String

    Public Overridable Property books As ICollection(Of book) = New HashSet(Of book)

End Class
