'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class KnightExchangeDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=KnightExchangeDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property authorities() As DbSet(Of authority)
    Public Overridable Property books() As DbSet(Of book)
    Public Overridable Property courses() As DbSet(Of cours)
    Public Overridable Property services() As DbSet(Of service)
    Public Overridable Property supplies() As DbSet(Of supply)
    Public Overridable Property users() As DbSet(Of user)

End Class
