'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class product
    Public Property product_id As Integer

    <Required>
    <Display(Name:="User ID")>
    Public Property user_id As Integer
    Public Property productinfo_id As Integer

    Public Overridable Property product_info As product_info
    Public Overridable Property user As user

End Class
