'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class product_info
    Public Property productinfo_id As Integer

    <Required>
    <Display(Name:="Product Name")>
    Public Property product_name As String

    <Required>
    <Display(Name:="Description")>
    Public Property product_description As String

    Public Overridable Property products As ICollection(Of product) = New HashSet(Of product)

End Class
