'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class user
    Public Property user_id As Integer
    Public Property user_lname As String
    Public Property user_fname As String
    Public Property user_email As String
    Public Property user_permission As String

    Public Overridable Property books As ICollection(Of book) = New HashSet(Of book)
    Public Overridable Property products As ICollection(Of product) = New HashSet(Of product)

End Class
